### ISSUE TITLE
IPv6 Support on cidr_ip in alibabacloudstack_security_group_rule

### ISSUE THREAD

**Issue by jksprattler** [aliyun/terraform-provider-alibabacloudstack#54]
Please add IPv6 Support on cidr_ip in alibabacloudstack_security_group_rule

https://registry.terraform.io/providers/aliyun/alibabacloudstack/latest/docs/resources/security_group_rule#cidr_ip
Only IPv4 is supported.

Without IPv6 support on the security group rules this makes it very difficult to maintain proper state for our infrastructure as this setting needs to be managed outside of Terraform.

**Comment by zshongyi** [comment]
The interfaces of apsarastack have differences between versions. Could you provide the current version of your environment for feedback?

**Comment by jksprattler** [comment]
```
terraform {
  required_providers {
    alicloud = {
      source  = "aliyun/alicloud"
      version = "1.212.0"
    }
  }
  required_version = ">= 1.3.4"
}
```

**Comment by zshongyi** [comment]
alicloud is Alibaba's public cloud services，alibabacloudstack is terraform provider with  Alibaba's Private Cloud Service。
You should ask the question in another Repository.
