### ISSUE TITLE
OSS Bucket Tags

### ISSUE THREAD

**Issue by swjn** [aliyun/terraform-provider-alibabacloudstack#56]
alibabacloud 有 bucket tags.. 我看到 alibabacloudstack 也有可是commented. 我需要这个， 可以用吗？

**Comment by zshongyi** [comment]
可以通过你们这边的TAM团队或者PDSA反馈一下你的云版本信息吗

**Comment by swjn** [comment]
Enterprise_v3.16.2, 构建号：17fca723-4497-47f8-bf99-da05f8b92fa4

**Comment by swjn** [comment]
我发现很多功能是已经有的了可是terraform哪的documentation没有提到。 你们有更新的documentation分享给我参考吗？
